doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                server_version: 11.5
                driver:   '%env(database_driver)%'
                host:     '%env(database_host)%'
                port:     '%env(database_port)%'
                dbname:   '%env(database_name)%'
                user:     '%env(database_user)%'
                password: '%env(database_password)%'
                charset:  UTF8
                mapping_types:
                    json: string
                    enum: string

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
