transformer:
    source: "xmls"
    target: "src/Nasajon/MDABundle"
    plugins:
        - angular1
        - symfony
compiler:
    namespace:
        dist: "web"
        MDA: "src/Nasajon/MDABundle/Resources/js"
        src: "assets/view/"
    sourcePath:
        - "@MDA"
        - "@src"
    targetPath: "src/Nasajon/MDABundle/Resources/js/"
    
webpack:
    files:
        - "assets/"


environment:
    host : "http://localhost"
