controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

mda:
    resource: ../../mda/Nasajon/MDABundle/Controller/
    type: annotation