nasajon_login_bundle:
    resource: "@NasajonLoginBundle/Resources/config/routing.yml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    prefix: /fosrouting

app:
   resource: "routing/app.yml"

api:
   resource: "routing/api.yml"
   type: rest
   prefix: /v2/api
   type: rest
    
  
index:
    type: rest
    resource: "Nasajon\\AppBundle\\Controller\\IndexController"
    defaults:
        html5mode: 'home'
    requirements:
        html5mode: .+
    
index_trailing_slash:
    path: /{tenant}/
    defaults:
        _controller:  FrameworkBundle:Template:template
        template: '@NasajonMDABundle/Resources/js/index.html'