security:
    access_decision_manager:
        strategy: unanimous
        allow_if_all_abstain:  true    
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        nasajon_provider:
            id: nasajon_login_bundle.saml_provider 
        apikeyprovider:
            id: nasajon_login_bundle_provider_api_key

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        
        api:
            pattern:   ^/v2/api
            stateless: true
            simple_preauth:
                authenticator: nasajon_login_bundle_authenticator_api_key
                provider: apikeyprovider
                

        secured_area:
            light_saml_sp:
                provider: nasajon_provider
                login_path: /saml/login
                check_path: /saml/login_check
                failure_path: security_error
                default_target_path: main_index
                always_use_default_target_path: true
            logout:
                path: logout
                target: default
                invalidate_session: false
                success_handler: nasajon_login_bundle.logout_handler                
            anonymous: ~
            logout_on_user_change: true
            
    access_control:
        - { path: ^/saml, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/fosrouting, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v2/api,       roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/,       roles: IS_AUTHENTICATED_FULLY }
