# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
    
services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    Nasajon\AppBundle\EventListener\MDAFixedAttributesListener:
        class : Nasajon\Diretorio\AppBundle\EventListener\MDAFixedAttributesListener
        tags:
           - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 100 }
        arguments :
            - "@security.token_storage"
            - "@nasajon_mda.fixed_attributes"

    session.memcached:
        class: Memcached
        calls:
            - [ addServer, [ "%env(memcached_host)%", "%env(memcached_port)%" ]]

    session.handler.memcached:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\MemcachedSessionHandler
        arguments: [ '@session.memcached', { prefix: 'ponto_session_', expiretime: 86400 } ]
