tenants:
    type: rest
    resource: "Nasajon\\MDABundle\\Controller\\TenantsController"
    name_prefix:   "tenants_"

clientes:
    type: rest
    resource: "Nasajon\\MDABundle\\Controller\\ClientesController"
    name_prefix:   "clientes_"

licencas:
    type: rest
    resource: "Nasajon\\MDABundle\\Controller\\LicencasController"
    name_prefix:   "licencas_"

licencas_modulos:
    type: rest
    resource: "Nasajon\\MDABundle\\Controller\\Licencas\\ModulosController"
    name_prefix:   "licencas_modulos_"

licencas_instalacoes:
    type: rest
    resource: "Nasajon\\MDABundle\\Controller\\Licencas\\InstalacoesController"
    name_prefix:   "licencas_instalacoes_"

sistemas:
    type: rest
    resource: "Nasajon\\MDABundle\\Controller\\SistemasController"
    name_prefix:   "sistemas_"

pacotes:
    type: rest
    resource: "Nasajon\\MDABundle\\Controller\\PacotesController"
    name_prefix:   "pacotes_"

atributos:
    type: rest
    resource: "Nasajon\\MDABundle\\Controller\\AtributosController"
    name_prefix:   "atributos_"

sistemas_planos:
    type: rest
    resource: "Nasajon\\MDABundle\\Controller\\Sistemas\\PlanosController"
    name_prefix:   "sistemas_planos_"

contas:
    type: rest
    resource: "Nasajon\\MDABundle\\Controller\\ContasController"
    name_prefix:   "contas_"

servidores:
    type: rest
    resource: "Nasajon\\MDABundle\\Controller\\ServidoresController"
    name_prefix:   "servidores_"

serviceproviders:
    type: rest
    resource: "Nasajon\\MDABundle\\Controller\\ServiceprovidersController"
    name_prefix:   "serviceproviders_"

diretoriopermissoes:
    type: rest
    resource: "Nasajon\\MDABundle\\Controller\\DiretoriopermissoesController"
    name_prefix:   "diretoriopermissoes_"